version: '3'

#docker run --name api-gym-pass -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e
#  POSTGRESQL_DATABASE=gym_pass -p 5432:5432  bitnami/postgresql
services:
  api-gym-pass:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gym_pass
    